//! Excel token classes of built-in functions (Excel 2013 and earlier):
//! return class and per-parameter class conversion, as used by the legacy
//! (pre-dynamic-array) evaluator. `(name, return, parameters, pairs)`; the
//! last parameter repeats, or the last two alternate when `pairs` is set.
//! Generated; sorted by name for binary search.
use super::Class::{self, A, R, V};
use super::{Param, RA, RO, RR, RX, VA, VO, VR, VV, VX};

#[rustfmt::skip]
pub(super) static FUNCTIONS: &[(&str, Class, &[Param], bool)] = &[
    ("ABS", V, &[VR], false),
    ("ACCRINT", V, &[RR], false),
    ("ACCRINTM", V, &[RR], false),
    ("ACOS", V, &[VR], false),
    ("ACOSH", V, &[VR], false),
    ("ACOT", V, &[VR], false),
    ("ACOTH", V, &[VR], false),
    ("ADDRESS", V, &[VR], false),
    ("AGGREGATE", V, &[VR, RO], false),
    ("AMORDEGRC", V, &[RR], false),
    ("AMORLINC", V, &[RR], false),
    ("AND", V, &[RX], false),
    ("ARABIC", V, &[VR], false),
    ("AREAS", V, &[RO], false),
    ("ASC", V, &[VR], false),
    ("ASIN", V, &[VR], false),
    ("ASINH", V, &[VR], false),
    ("ATAN", V, &[VR], false),
    ("ATAN2", V, &[VR], false),
    ("ATANH", V, &[VR], false),
    ("AVEDEV", V, &[RX], false),
    ("AVERAGE", V, &[RX], false),
    ("AVERAGEA", V, &[RX], false),
    ("AVERAGEIF", V, &[RO, VR, RO], false),
    ("AVERAGEIFS", V, &[RO, RO, VR], true),
    ("BAHTTEXT", V, &[VR], false),
    ("BASE", V, &[VR], false),
    ("BESSELI", V, &[RR], false),
    ("BESSELJ", V, &[RR], false),
    ("BESSELK", V, &[RR], false),
    ("BESSELY", V, &[RR], false),
    ("BETA.DIST", V, &[VR], false),
    ("BETA.INV", V, &[VR], false),
    ("BETADIST", V, &[VR], false),
    ("BETAINV", V, &[VR], false),
    ("BIN2DEC", V, &[RR], false),
    ("BIN2HEX", V, &[RR], false),
    ("BIN2OCT", V, &[RR], false),
    ("BINOM.DIST", V, &[VR], false),
    ("BINOM.DIST.RANGE", V, &[VR], false),
    ("BINOM.INV", V, &[VR], false),
    ("BINOMDIST", V, &[VR], false),
    ("BITAND", V, &[VR], false),
    ("BITLSHIFT", V, &[VR], false),
    ("BITOR", V, &[VR], false),
    ("BITRSHIFT", V, &[VR], false),
    ("BITXOR", V, &[VR], false),
    ("CEILING", V, &[VR], false),
    ("CEILING.MATH", V, &[VR], false),
    ("CEILING.PRECISE", V, &[VR], false),
    ("CELL", V, &[VV, RO], false),
    ("CHAR", V, &[VR], false),
    ("CHIDIST", V, &[VR], false),
    ("CHIINV", V, &[VR], false),
    ("CHISQ.DIST", V, &[VR], false),
    ("CHISQ.DIST.RT", V, &[VR], false),
    ("CHISQ.INV", V, &[VR], false),
    ("CHISQ.INV.RT", V, &[VR], false),
    ("CHISQ.TEST", V, &[VA], false),
    ("CHITEST", V, &[VA], false),
    ("CHOOSE", R, &[VO, RO], false),
    ("CLEAN", V, &[VR], false),
    ("CODE", V, &[VR], false),
    ("COLUMN", V, &[RO], false),
    ("COLUMNS", V, &[RO], false),
    ("COMBIN", V, &[VR], false),
    ("COMBINA", V, &[VR], false),
    ("COMPLEX", V, &[RR], false),
    ("CONCATENATE", V, &[VR], false),
    ("CONFIDENCE", V, &[VR], false),
    ("CONFIDENCE.NORM", V, &[VR], false),
    ("CONFIDENCE.T", V, &[VR], false),
    ("CONVERT", V, &[RR], false),
    ("CORREL", V, &[VA], false),
    ("COS", V, &[VR], false),
    ("COSH", V, &[VR], false),
    ("COT", V, &[VR], false),
    ("COTH", V, &[VR], false),
    ("COUNT", V, &[RX], false),
    ("COUNTA", V, &[RX], false),
    ("COUNTBLANK", V, &[RO], false),
    ("COUNTIF", V, &[RO, VR], false),
    ("COUNTIFS", V, &[RO, VR], true),
    ("COUPDAYBS", V, &[RR], false),
    ("COUPDAYS", V, &[RR], false),
    ("COUPDAYSNC", V, &[RR], false),
    ("COUPNCD", V, &[RR], false),
    ("COUPNUM", V, &[RR], false),
    ("COUPPCD", V, &[RR], false),
    ("COVAR", V, &[VA], false),
    ("COVARIANCE.P", V, &[VA], false),
    ("COVARIANCE.S", V, &[VA], false),
    ("CRITBINOM", V, &[VR], false),
    ("CSC", V, &[VR], false),
    ("CSCH", V, &[VR], false),
    ("CUMIPMT", V, &[RR], false),
    ("CUMPRINC", V, &[RR], false),
    ("DATE", V, &[VR], false),
    ("DATEDIF", V, &[VR], false),
    ("DATESTRING", V, &[VR], false),
    ("DATEVALUE", V, &[VR], false),
    ("DAVERAGE", V, &[RO, RR], false),
    ("DAY", V, &[VR], false),
    ("DAYS", V, &[VR], false),
    ("DAYS360", V, &[VR], false),
    ("DB", V, &[VR], false),
    ("DBCS", V, &[VR], false),
    ("DCOUNT", V, &[RO, RR], false),
    ("DCOUNTA", V, &[RO, RR], false),
    ("DDB", V, &[VR], false),
    ("DEC2BIN", V, &[RR], false),
    ("DEC2HEX", V, &[RR], false),
    ("DEC2OCT", V, &[RR], false),
    ("DECIMAL", V, &[VR], false),
    ("DEGREES", V, &[VR], false),
    ("DELTA", V, &[RR], false),
    ("DEVSQ", V, &[RX], false),
    ("DGET", V, &[RO, RR], false),
    ("DISC", V, &[RR], false),
    ("DMAX", V, &[RO, RR], false),
    ("DMIN", V, &[RO, RR], false),
    ("DOLLAR", V, &[VR], false),
    ("DOLLARDE", V, &[RR], false),
    ("DOLLARFR", V, &[RR], false),
    ("DPRODUCT", V, &[RO, RR], false),
    ("DSTDEV", V, &[RO, RR], false),
    ("DSTDEVP", V, &[RO, RR], false),
    ("DSUM", V, &[RO, RR], false),
    ("DURATION", V, &[RR], false),
    ("DVAR", V, &[RO, RR], false),
    ("DVARP", V, &[RO, RR], false),
    ("EDATE", V, &[RR], false),
    ("EFFECT", V, &[RR], false),
    ("ENCODEURL", V, &[VR], false),
    ("EOMONTH", V, &[RR], false),
    ("ERF", V, &[RR], false),
    ("ERF.PRECISE", V, &[VR], false),
    ("ERFC", V, &[RR], false),
    ("ERFC.PRECISE", V, &[VR], false),
    ("ERROR.TYPE", V, &[VR], false),
    ("EVEN", V, &[VR], false),
    ("EXACT", V, &[VR], false),
    ("EXP", V, &[VR], false),
    ("EXPON.DIST", V, &[VR], false),
    ("EXPONDIST", V, &[VR], false),
    ("F.DIST", V, &[VR], false),
    ("F.DIST.RT", V, &[VR], false),
    ("F.INV", V, &[VR], false),
    ("F.INV.RT", V, &[VR], false),
    ("F.TEST", V, &[VA], false),
    ("FACT", V, &[VR], false),
    ("FACTDOUBLE", V, &[RR], false),
    ("FALSE", V, &[], false),
    ("FDIST", V, &[VR], false),
    ("FILTERXML", V, &[VR], false),
    ("FIND", V, &[VR], false),
    ("FINDB", V, &[VR], false),
    ("FINV", V, &[VR], false),
    ("FISHER", V, &[VR], false),
    ("FISHERINV", V, &[VR], false),
    ("FIXED", V, &[VR], false),
    ("FLOOR", V, &[VR], false),
    ("FLOOR.MATH", V, &[VR], false),
    ("FLOOR.PRECISE", V, &[VR], false),
    ("FORECAST", V, &[VR, VA], false),
    ("FORMULATEXT", V, &[RO], false),
    ("FREQUENCY", A, &[RA], false),
    ("FTEST", V, &[VA], false),
    ("FV", V, &[VR], false),
    ("FVSCHEDULE", V, &[RR, RX], false),
    ("GAMMA", V, &[VR], false),
    ("GAMMA.DIST", V, &[VR], false),
    ("GAMMA.INV", V, &[VR], false),
    ("GAMMADIST", V, &[VR], false),
    ("GAMMAINV", V, &[VR], false),
    ("GAMMALN", V, &[VR], false),
    ("GAMMALN.PRECISE", V, &[VR], false),
    ("GAUSS", V, &[VR], false),
    ("GCD", V, &[RX], false),
    ("GEOMEAN", V, &[RX], false),
    ("GESTEP", V, &[RR], false),
    ("GROWTH", A, &[RA, RA, RA, VV], false),
    ("HARMEAN", V, &[RX], false),
    ("HEX2BIN", V, &[RR], false),
    ("HEX2DEC", V, &[RR], false),
    ("HEX2OCT", V, &[RR], false),
    ("HLOOKUP", V, &[VV, RO, RO, VV], false),
    ("HOUR", V, &[VR], false),
    ("HYPERLINK", V, &[VV, VO], false),
    ("HYPGEOM.DIST", V, &[VR], false),
    ("HYPGEOMDIST", V, &[VR], false),
    ("IF", R, &[VO, RO], false),
    ("IFERROR", V, &[VO, RO], false),
    ("IFNA", V, &[VO, RO], false),
    ("IMABS", V, &[RR], false),
    ("IMAGINARY", V, &[RR], false),
    ("IMARGUMENT", V, &[RR], false),
    ("IMCONJUGATE", V, &[RR], false),
    ("IMCOS", V, &[RR], false),
    ("IMCOSH", V, &[VR], false),
    ("IMCOT", V, &[VR], false),
    ("IMCSC", V, &[VR], false),
    ("IMCSCH", V, &[VR], false),
    ("IMDIV", V, &[RR], false),
    ("IMEXP", V, &[RR], false),
    ("IMLN", V, &[RR], false),
    ("IMLOG10", V, &[RR], false),
    ("IMLOG2", V, &[RR], false),
    ("IMPOWER", V, &[RR], false),
    ("IMPRODUCT", V, &[RX], false),
    ("IMREAL", V, &[RR], false),
    ("IMSEC", V, &[VR], false),
    ("IMSECH", V, &[VR], false),
    ("IMSIN", V, &[RR], false),
    ("IMSINH", V, &[VR], false),
    ("IMSQRT", V, &[RR], false),
    ("IMSUB", V, &[RR], false),
    ("IMSUM", V, &[RX], false),
    ("IMTAN", V, &[VR], false),
    ("INDEX", R, &[RA, VV], false),
    ("INDIRECT", R, &[VR], false),
    ("INT", V, &[VR], false),
    ("INTERCEPT", V, &[VA], false),
    ("INTRATE", V, &[RR], false),
    ("IPMT", V, &[VR], false),
    ("IRR", V, &[RA, VR], false),
    ("ISBLANK", V, &[VR], false),
    ("ISERR", V, &[VR], false),
    ("ISERROR", V, &[VR], false),
    ("ISEVEN", V, &[RR], false),
    ("ISFORMULA", V, &[RO], false),
    ("ISLOGICAL", V, &[VR], false),
    ("ISNA", V, &[VR], false),
    ("ISNONTEXT", V, &[VR], false),
    ("ISNUMBER", V, &[VR], false),
    ("ISO.CEILING", V, &[VR], false),
    ("ISODD", V, &[RR], false),
    ("ISOWEEKNUM", V, &[VR], false),
    ("ISPMT", V, &[VR], false),
    ("ISREF", V, &[RX], false),
    ("ISTEXT", V, &[VR], false),
    ("ISTHAIDIGIT", V, &[VR], false),
    ("KURT", V, &[RX], false),
    ("LARGE", V, &[RX, VR], false),
    ("LCM", V, &[RX], false),
    ("LEFT", V, &[VR], false),
    ("LEFTB", V, &[VR], false),
    ("LEN", V, &[VR], false),
    ("LENB", V, &[VR], false),
    ("LINEST", A, &[RA, RA, VV], false),
    ("LN", V, &[VR], false),
    ("LOG", V, &[VR], false),
    ("LOG10", V, &[VR], false),
    ("LOGEST", A, &[RA, RA, VV], false),
    ("LOGINV", V, &[VR], false),
    ("LOGNORM.DIST", V, &[VR], false),
    ("LOGNORM.INV", V, &[VR], false),
    ("LOGNORMDIST", V, &[VR], false),
    ("LOOKUP", V, &[VR, RA], false),
    ("LOWER", V, &[VR], false),
    ("MATCH", V, &[VR, RX, RR], false),
    ("MAX", V, &[RX], false),
    ("MAXA", V, &[RX], false),
    ("MDETERM", V, &[VA], false),
    ("MDURATION", V, &[RR], false),
    ("MEDIAN", V, &[RX], false),
    ("MID", V, &[VR], false),
    ("MIDB", V, &[VR], false),
    ("MIN", V, &[RX], false),
    ("MINA", V, &[RX], false),
    ("MINUTE", V, &[VR], false),
    ("MINVERSE", A, &[VA], false),
    ("MIRR", V, &[RA, VR], false),
    ("MMULT", A, &[VA], false),
    ("MOD", V, &[VR], false),
    ("MODE", V, &[VA], false),
    ("MODE.MULT", V, &[VA], false),
    ("MODE.SNGL", V, &[VA], false),
    ("MONTH", V, &[VR], false),
    ("MROUND", V, &[RR], false),
    ("MULTINOMIAL", V, &[RX], false),
    ("MUNIT", A, &[VR], false),
    ("N", V, &[RO], false),
    ("NA", V, &[], false),
    ("NEGBINOM.DIST", V, &[VR], false),
    ("NEGBINOMDIST", V, &[VR], false),
    ("NETWORKDAYS", V, &[RR, RR, RX], false),
    ("NETWORKDAYS.INTL", V, &[VR, VR, VR, RX], false),
    ("NOMINAL", V, &[RR], false),
    ("NORM.DIST", V, &[VR], false),
    ("NORM.INV", V, &[VR], false),
    ("NORM.S.DIST", V, &[VR], false),
    ("NORM.S.INV", V, &[VR], false),
    ("NORMDIST", V, &[VR], false),
    ("NORMINV", V, &[VR], false),
    ("NORMSDIST", V, &[VR], false),
    ("NORMSINV", V, &[VR], false),
    ("NOT", V, &[VR], false),
    ("NOW", V, &[], false),
    ("NPER", V, &[VR], false),
    ("NPV", V, &[VR, RX], false),
    ("NUMBERSTRING", V, &[VR], false),
    ("NUMBERVALUE", V, &[VR], false),
    ("OCT2BIN", V, &[RR], false),
    ("OCT2DEC", V, &[RR], false),
    ("OCT2HEX", V, &[RR], false),
    ("ODD", V, &[VR], false),
    ("ODDFPRICE", V, &[RR], false),
    ("ODDFYIELD", V, &[RR], false),
    ("ODDLPRICE", V, &[RR], false),
    ("ODDLYIELD", V, &[RR], false),
    ("OFFSET", R, &[RO, VR], false),
    ("OR", V, &[RX], false),
    ("PDURATION", V, &[VR], false),
    ("PEARSON", V, &[VA], false),
    ("PERCENTILE", V, &[RX, VR], false),
    ("PERCENTILE.EXC", V, &[RX, VR], false),
    ("PERCENTILE.INC", V, &[RX, VR], false),
    ("PERCENTRANK", V, &[RX, VR, VR], false),
    ("PERCENTRANK.EXC", V, &[RX, VR, VR], false),
    ("PERCENTRANK.INC", V, &[RX, VR, VR], false),
    ("PERMUT", V, &[VR], false),
    ("PERMUTATIONA", V, &[VR], false),
    ("PHI", V, &[VR], false),
    ("PHONETIC", V, &[RO], false),
    ("PI", V, &[], false),
    ("PMT", V, &[VR], false),
    ("POISSON", V, &[VR], false),
    ("POISSON.DIST", V, &[VR], false),
    ("POWER", V, &[VR], false),
    ("PPMT", V, &[VR], false),
    ("PRICE", V, &[RR], false),
    ("PRICEDISC", V, &[RR], false),
    ("PRICEMAT", V, &[RR], false),
    ("PROB", V, &[VA, VA, VR], false),
    ("PRODUCT", V, &[RX], false),
    ("PROPER", V, &[VR], false),
    ("PV", V, &[VR], false),
    ("QUARTILE", V, &[RX, VR], false),
    ("QUARTILE.EXC", V, &[RX, VR], false),
    ("QUARTILE.INC", V, &[RX, VR], false),
    ("QUOTIENT", V, &[RR], false),
    ("RADIANS", V, &[VR], false),
    ("RAND", V, &[], false),
    ("RANDBETWEEN", V, &[RR], false),
    ("RANK", V, &[VR, RO, VR], false),
    ("RANK.AVG", V, &[VR, RO, VR], false),
    ("RANK.EQ", V, &[VR, RO, VR], false),
    ("RATE", V, &[VR], false),
    ("RECEIVED", V, &[RR], false),
    ("REPLACE", V, &[VR], false),
    ("REPLACEB", V, &[VR], false),
    ("REPT", V, &[VR], false),
    ("RIGHT", V, &[VR], false),
    ("RIGHTB", V, &[VR], false),
    ("ROMAN", V, &[VR], false),
    ("ROUND", V, &[VR], false),
    ("ROUNDBAHTDOWN", V, &[VR], false),
    ("ROUNDBAHTUP", V, &[VR], false),
    ("ROUNDDOWN", V, &[VR], false),
    ("ROUNDUP", V, &[VR], false),
    ("ROW", V, &[RO], false),
    ("ROWS", V, &[RO], false),
    ("RRI", V, &[VR], false),
    ("RSQ", V, &[VA], false),
    ("SEARCH", V, &[VR], false),
    ("SEARCHB", V, &[VR], false),
    ("SEC", V, &[VR], false),
    ("SECH", V, &[VR], false),
    ("SECOND", V, &[VR], false),
    ("SERIESSUM", V, &[RR, RR, RR, RX], false),
    ("SHEET", V, &[RO], false),
    ("SHEETS", V, &[RO], false),
    ("SIGN", V, &[VR], false),
    ("SIN", V, &[VR], false),
    ("SINH", V, &[VR], false),
    ("SKEW", V, &[RX], false),
    ("SKEW.P", V, &[RX], false),
    ("SLN", V, &[VR], false),
    ("SLOPE", V, &[VA], false),
    ("SMALL", V, &[RX, VR], false),
    ("SQRT", V, &[VR], false),
    ("SQRTPI", V, &[RR], false),
    ("STANDARDIZE", V, &[VR], false),
    ("STDEV", V, &[RX], false),
    ("STDEV.P", V, &[RX], false),
    ("STDEV.S", V, &[RX], false),
    ("STDEVA", V, &[RX], false),
    ("STDEVP", V, &[RX], false),
    ("STDEVPA", V, &[RX], false),
    ("STEYX", V, &[VA], false),
    ("SUBSTITUTE", V, &[VR], false),
    ("SUBTOTAL", V, &[VR, RO], false),
    ("SUM", V, &[RX], false),
    ("SUMIF", V, &[RO, VR, RO], false),
    ("SUMIFS", V, &[RO, RO, VR], true),
    ("SUMPRODUCT", V, &[VA], false),
    ("SUMSQ", V, &[RX], false),
    ("SUMX2MY2", V, &[VA], false),
    ("SUMX2PY2", V, &[VA], false),
    ("SUMXMY2", V, &[VA], false),
    ("SYD", V, &[VR], false),
    ("T", V, &[RO], false),
    ("T.DIST", V, &[VR], false),
    ("T.DIST.2T", V, &[VR], false),
    ("T.DIST.RT", V, &[VR], false),
    ("T.INV", V, &[VR], false),
    ("T.INV.2T", V, &[VR], false),
    ("T.TEST", V, &[VA, VA, VR], false),
    ("TAN", V, &[VR], false),
    ("TANH", V, &[VR], false),
    ("TBILLEQ", V, &[RR], false),
    ("TBILLPRICE", V, &[RR], false),
    ("TBILLYIELD", V, &[RR], false),
    ("TDIST", V, &[VR], false),
    ("TEXT", V, &[VR], false),
    ("THAIDAYOFWEEK", V, &[VR], false),
    ("THAIDIGIT", V, &[VR], false),
    ("THAIMONTHOFYEAR", V, &[VR], false),
    ("THAINUMSOUND", V, &[VR], false),
    ("THAINUMSTRING", V, &[VR], false),
    ("THAISTRINGLENGTH", V, &[VR], false),
    ("THAIYEAR", V, &[VR], false),
    ("TIME", V, &[VR], false),
    ("TIMEVALUE", V, &[VR], false),
    ("TINV", V, &[VR], false),
    ("TODAY", V, &[], false),
    ("TRANSPOSE", A, &[VO], false),
    ("TREND", A, &[RA, RA, RA, VV], false),
    ("TRIM", V, &[VR], false),
    ("TRIMMEAN", V, &[RX, VR], false),
    ("TRUE", V, &[], false),
    ("TRUNC", V, &[VR], false),
    ("TTEST", V, &[VA, VA, VR], false),
    ("TYPE", V, &[VX], false),
    ("UNICHAR", V, &[VR], false),
    ("UNICODE", V, &[VR], false),
    ("UPPER", V, &[VR], false),
    ("USDOLLAR", V, &[VR], false),
    ("VALUE", V, &[VR], false),
    ("VAR", V, &[RX], false),
    ("VAR.P", V, &[RX], false),
    ("VAR.S", V, &[RX], false),
    ("VARA", V, &[RX], false),
    ("VARP", V, &[RX], false),
    ("VARPA", V, &[RX], false),
    ("VDB", V, &[VR], false),
    ("VLOOKUP", V, &[VV, RO, RO, VV], false),
    ("WEBSERVICE", V, &[VR], false),
    ("WEEKDAY", V, &[VR], false),
    ("WEEKNUM", V, &[RR], false),
    ("WEIBULL", V, &[VR], false),
    ("WEIBULL.DIST", V, &[VR], false),
    ("WORKDAY", V, &[RR, RR, RX], false),
    ("WORKDAY.INTL", V, &[VR, VR, VR, RX], false),
    ("XIRR", V, &[RX, RX, RR], false),
    ("XNPV", V, &[RR, RX, RX], false),
    ("XOR", V, &[RX], false),
    ("YEAR", V, &[VR], false),
    ("YEARFRAC", V, &[RR], false),
    ("YIELD", V, &[RR], false),
    ("YIELDDISC", V, &[RR], false),
    ("YIELDMAT", V, &[RR], false),
    ("Z.TEST", V, &[RX, VR], false),
    ("ZTEST", V, &[RX, VR], false),
];
