[package]
name = "formualizer-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
formualizer-core = { path = "../formualizer-core" }
formualizer-macros  = { path = "../formualizer-macros" }
formualizer-common = { path = "../formualizer-common" }
once_cell = "1.21.3"
