[package]
name = "formualizer-eval"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused_variables = "allow"
dead_code = "allow"

[lints.clippy]
too_many_arguments = "allow"
only_used_in_recursion = "allow"

[dependencies]
formualizer-core = { path = "../formualizer-core" }
formualizer-macros  = { path = "../formualizer-macros" }
formualizer-common = { path = "../formualizer-common" }
once_cell = "1.21.3"
rustc-hash = "1.1"
rand = "0.8.5"
rayon = "1.8"
dashmap = "6.1.0"
chrono = "0.4.41"
bitflags = "2.9.1"
bumpalo = { version = "3.16", features = ["collections"] }
smallvec = "1.13"
