[package]
name = "formualizer-io"
version = "0.1.0"
edition = "2024"


[dependencies]
formualizer-core = { path = "../formualizer-core" }
formualizer-common = { path = "../formualizer-common" }
formualizer-eval = { path = " ../formualizer-eval" }