import datetime
from typing import Any, Mapping, Optional, Union

class Workbook:
    def set_actor_id(self, actor_id: Optional[str] = ...) -> None: ...
    def set_correlation_id(self, correlation_id: Optional[str] = ...) -> None: ...
    def set_reason(self, reason: Optional[str] = ...) -> None: ...

class SheetPortSession:
    def evaluate_once(
        self,
        *,
        freeze_volatile: bool = ...,
        rng_seed: Optional[int] = ...,
        deterministic_timestamp_utc: Optional[datetime.datetime] = ...,
        deterministic_timezone: Optional[Union[str, int]] = ...,
    ) -> Mapping[str, Any]: ...

class EvaluationConfig:
    def set_case_sensitive_names(self, value: bool) -> None: ...
    def get_case_sensitive_names(self) -> bool: ...
    def set_case_sensitive_tables(self, value: bool) -> None: ...
    def get_case_sensitive_tables(self) -> bool: ...
